### ISSUE TITLE
🚨 Link to instagram is invalid! 🚨 

### ISSUE THREAD

**Issue by kayooliveira** [gabrielcardosodev/cv#1]
# Redirect link to instagram is invalid! 🚨 

> I clicked on the link to be redirected to your instagram and it didn't work. It took me to a non-existent url.

![image](https://user-images.githubusercontent.com/35928107/236656886-5e6b8d25-a243-452d-9a77-daff530dbf8c.png)

### look:

> It looks like you typed your username wrong, you wrote **carjdoso** instead of **cardjoso**

![image](https://user-images.githubusercontent.com/35928107/236656872-a358058c-c41f-4e26-97ff-566c68c38489.png)
![image](https://user-images.githubusercontent.com/35928107/236656876-e6a4cbd5-d465-4dd8-bfc1-144530a80efa.png)

**Comment by gabrielcardosodev** [comment]
https://github.com/gabrielcardosodev/cv/commit/92a187f0f3dbdadfff32228761c699f6011f76d2
